version: "3"
services:
  local_db:
    # 컨테이너 이름을 주고 싶다면 작성한다
    # container_name: test_database
    image: mysql:8
    environment:
      MYSQL_DATABASE: project
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: 1234
    ports:
      - 3333:3306

  test_application:
    build: .
    ports:
      - 8083:8083
    depends_on:
      - local_db