spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://busan-real-db.ceuuonjcjyne.ap-northeast-2.rds.amazonaws.com:3306/project?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
    username: frank
    password: wlgh1948
    connection-test-query: SELECT NOW() FROM dual
    hikari.pool-name: TestHikariPool

  jpa:
    database: mysql
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
      show-sql: true